import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import { ArrowRight, CalendarDays, Plus, Weight, X } from "lucide-react"
import { Link } from "react-router-dom"
import apiRequest from "../lib/api"
import { useAuth } from "../context/AuthContext"
import Logo from "../components/Logo"
import EmptyState from "../components/EmptyState"

const icons = { Dog: "🐕", Cat: "🐈", Bird: "🦜", Rabbit: "🐇", Other: "🐾" }
const age = (date) => { if (!date) return "Not recorded"; const years = Math.floor((Date.now() - new Date(date)) / 31557600000); return `${Math.max(0, years)} year${years === 1 ? "" : "s"}` }
const emptyPet = { name: "", species: "Dog", breed: "", gender: "Unknown", dateOfBirth: "", weight: "", color: "", microchipId: "", notes: "" }

export default function Pets() {
  const { logout } = useAuth()
  const [pets, setPets] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showModal, setShowModal] = useState(false)
  const loadPets = () => apiRequest("/pets").then((data) => setPets(data.pets)).catch((err) => setError(err.message)).finally(() => setLoading(false))
  useEffect(() => { loadPets() }, [])
  const addPet = async (pet) => { const response = await apiRequest("/pets", { method: "POST", body: JSON.stringify(pet) }); setPets((current) => [response.pet, ...current]); setShowModal(false) }
  return <div className="min-h-screen bg-[#f7f8f5] text-[#17221e]"><main className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-10"><header className="flex items-center justify-between"><Link to="/dashboard"><Logo size={30} textClassName="text-sm font-semibold" /></Link><div className="flex items-center gap-5"><Link to="/dashboard" className="text-xs font-semibold text-[#52615a]">Dashboard</Link><button onClick={logout} className="text-xs font-semibold text-[#52615a]">Sign out</button></div></header><div className="mt-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4c806c]">Pet profiles</p><h1 className="mt-2 text-3xl font-semibold">Your companions</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#718079]">Keep their appointments and health information together.</p></div><button onClick={() => setShowModal(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#173b31] px-5 py-3 text-sm font-semibold text-white"><Plus size={16} />Add Pet</button></div>{error && <p className="mt-6 rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading ? [1,2,3].map((item) => <div key={item} className="h-96 animate-pulse rounded-[2.5rem] bg-white" />) : pets.map((pet, index) => <PetCard key={pet._id} pet={pet} index={index} />)}{!loading && pets.length === 0 && <Empty onAdd={() => setShowModal(true)} />}{!loading && pets.length > 0 && <button onClick={() => setShowModal(true)} className="min-h-80 rounded-[2.5rem] border-2 border-dashed border-[#d4ded7] p-7 text-center text-sm font-semibold text-[#52615a] hover:bg-white"><Plus className="mx-auto mb-3 text-[#4c806c]" />Add another pet</button>}</div></main>{showModal && <PetModal onClose={() => setShowModal(false)} onSave={addPet} />}</div>
}
function PetCard({ pet, index }) { return <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:index*.06}} className="overflow-hidden rounded-[2.5rem] border border-[#e1e7e2] bg-white"><div className="flex h-44 items-center justify-center bg-[#edf3ee] text-7xl">{icons[pet.species]}</div><div className="p-6"><div className="flex justify-between"><div><h2 className="text-2xl font-semibold">{pet.name}</h2><p className="mt-1 text-sm text-[#718079]">{[pet.breed,pet.species].filter(Boolean).join(" · ")}</p></div><span className="rounded-full bg-[#f3f5f3] px-3 py-1.5 text-xs text-[#718079]">{pet.gender}</span></div><div className="mt-6 grid grid-cols-2 gap-3"><Metric icon={CalendarDays} label="Age" value={age(pet.dateOfBirth)} /><Metric icon={Weight} label="Weight" value={pet.weight ? `${pet.weight} kg` : "Not recorded"} /></div><Link to={`/pets/${pet._id}`} className="mt-6 flex items-center justify-center gap-2 rounded-full border border-[#dfe6e1] px-5 py-3 text-xs font-semibold hover:bg-[#f5f8f5]">View Pet Profile <ArrowRight size={14} /></Link></div></motion.div> }
function Metric({icon:Icon,label,value}) { return <div className="rounded-2xl bg-[#f6f8f6] p-3"><p className="flex items-center gap-1 text-[10px] uppercase tracking-wider text-[#87928c]"><Icon size={12}/>{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div> }
function Empty({onAdd}) { return <div className="col-span-full"><EmptyState title="No pets yet" description="Add your first companion to start managing their care." action={<button onClick={onAdd} className="rounded-full bg-[#173b31] px-5 py-3 text-xs font-semibold text-white">Add Pet</button>} /></div> }
function PetModal({onClose,onSave}) { const [form,setForm]=useState(emptyPet); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const update=(field,value)=>setForm((current)=>({...current,[field]:value})); const submit=async(event)=>{event.preventDefault();setSaving(true);setError("");try{await onSave(form)}catch(err){setError(err.message||"Unable to add pet.")}finally{setSaving(false)}}; return <div className="fixed inset-0 z-50 grid place-items-center bg-[#10241d]/30 p-4 backdrop-blur-sm"><motion.form initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-7 sm:p-9"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4c806c]">New companion</p><h2 className="mt-2 text-2xl font-semibold">Add a pet</h2><p className="mt-2 text-sm text-[#718079]">Tell us a little about your companion.</p></div><button type="button" onClick={onClose}><X /></button></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Pet name" value={form.name} onChange={(v)=>update("name",v)} required /><Select label="Species" value={form.species} onChange={(v)=>update("species",v)} options={["Dog","Cat"]}/><Field label="Breed" value={form.breed} onChange={(v)=>update("breed",v)} /><Select label="Gender" value={form.gender} onChange={(v)=>update("gender",v)} options={["Male","Female","Unknown"]}/></div><h3 className="mt-8 text-sm font-semibold">Health information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Date of birth" type="date" value={form.dateOfBirth} onChange={(v)=>update("dateOfBirth",v)} /><Field label="Weight (kg)" type="number" value={form.weight} onChange={(v)=>update("weight",v)} /><Field label="Color" value={form.color} onChange={(v)=>update("color",v)} /><Field label="Microchip ID" value={form.microchipId} onChange={(v)=>update("microchipId",v)} /></div><label className="mt-4 block text-xs font-semibold text-[#52615a]">Notes<textarea value={form.notes} onChange={(e)=>update("notes",e.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-[#dfe6e1] p-3 text-sm" placeholder="Anything we should know..." /></label><div className="mt-7 flex gap-3"><button type="button" onClick={onClose} className="flex-1 rounded-full border py-3 text-sm font-semibold">Cancel</button><button disabled={saving} className="flex-1 rounded-full bg-[#173b31] py-3 text-sm font-semibold text-white">{saving?"Adding…":"Add Pet"}</button></div></motion.form></div> }
function Field({label,type="text",value,onChange,required}) { return <label className="block text-xs font-semibold text-[#52615a]">{label}<input required={required} type={type} min={type==="number"?"0":undefined} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-[#dfe6e1] bg-[#fbfcfb] px-4 py-3 text-sm" /></label> }
function Select({label,value,onChange,options}) { return <label className="block text-xs font-semibold text-[#52615a]">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-[#dfe6e1] bg-[#fbfcfb] px-4 py-3 text-sm">{options.map((option)=><option key={option}>{option}</option>)}</select></label> }
