import { useEffect, useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { ArrowLeft, Check, Clock3, FileText, Heart, History, Pill, Plus, Save, Stethoscope, Video, X } from "lucide-react"
import { Link, useParams } from "react-router-dom"
import apiRequest from "../../lib/api"
import { useAuth } from "../../context/AuthContext"

const emptyForm = { symptoms: "", notes: "", diagnosis: "", treatment: "", vitals: { weight: "", temperature: "", heartRate: "", respiratoryRate: "" }, prescriptionItems: [{ medication: "", dosage: "", frequency: "", duration: "" }] }
const dateText = (date) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(date))
const ageText = (date) => { if (!date) return "Not recorded"; const years = Math.floor((Date.now() - new Date(date)) / 31557600000); return `${Math.max(years, 0)} year${years === 1 ? "" : "s"}` }

export default function PatientVisit() {
  const { id } = useParams()
  const { logout } = useAuth()
  const [data, setData] = useState(null)
  const [form, setForm] = useState(emptyForm)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [completeOpen, setCompleteOpen] = useState(false)
  const [completed, setCompleted] = useState(false)
  const [selectedRecord, setSelectedRecord] = useState(null)

  useEffect(() => {
    setLoading(true)
    apiRequest(`/appointments/${id}`).then((response) => {
      setData(response)
      const existing = response.medicalRecords.find((record) => record.appointment === id || record.appointment?._id === id)
      if (existing) setForm({ symptoms: existing.symptoms || "", notes: existing.notes || "", diagnosis: existing.diagnosis || "", treatment: existing.treatment || "", vitals: { ...emptyForm.vitals, ...(existing.vitals || {}) }, prescriptionItems: existing.prescriptionItems?.length ? existing.prescriptionItems : emptyForm.prescriptionItems })
      else if (response.appointment.pet.weight) setForm((current) => ({ ...current, vitals: { ...current.vitals, weight: response.appointment.pet.weight } }))
    }).catch((requestError) => setError(requestError.message || "Unable to load this consultation.")).finally(() => setLoading(false))
  }, [id])

  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  const updateVital = (field, value) => setForm((current) => ({ ...current, vitals: { ...current.vitals, [field]: value } }))
  const updatePrescription = (index, field, value) => setForm((current) => ({ ...current, prescriptionItems: current.prescriptionItems.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }))
  const save = async () => {
    setSaving(true); setError("")
    try { const response = await apiRequest("/medical-records", { method: "POST", body: JSON.stringify({ appointmentId: id, ...form }) }); setData((current) => ({ ...current, medicalRecords: [response.medicalRecord, ...current.medicalRecords.filter((record) => record.appointment !== id && record.appointment?._id !== id)] })); setSaved(true); setTimeout(() => setSaved(false), 3000); return true } catch (requestError) { setError(requestError.message || "Unable to save the medical record."); return false } finally { setSaving(false) }
  }
  const complete = async () => { try { if (!(await save())) return; const response = await apiRequest(`/appointments/${id}/complete`, { method: "PATCH" }); setData((current) => ({ ...current, appointment: response.appointment })); setCompleted(true); setCompleteOpen(false) } catch (requestError) { setError(requestError.message || "Unable to complete the appointment."); setCompleteOpen(false) } }

  if (loading) return <LoadingWorkspace />
  if (error && !data) return <Message title="You’re not authorized to access this consultation." detail={error} />
  const { appointment, medicalRecords } = data
  const pet = appointment.pet
  const isOnline = appointment.type === "online"

  return <div className="min-h-screen bg-[#f7f8f5] text-[#17221e]"><main className="mx-auto max-w-7xl px-5 py-6 md:px-8 md:py-8">
    <header className="flex flex-wrap items-center justify-between gap-4"><Link to="/doctor" className="flex items-center gap-2 text-sm font-semibold text-[#52615a]"><ArrowLeft size={16} />Back to appointments</Link><div className="flex items-center gap-3"><span className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-[#52615a]"><Clock3 className="mr-1 inline" size={13} />{appointment.startTime}</span><button onClick={logout} className="text-xs font-semibold text-[#52615a]">Sign out</button></div></header>
    {error && <p className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}
    {completed && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#e4f1e7] px-5 py-4 text-sm text-[#397051]"><span><Check className="mr-2 inline" size={16} />Appointment completed and medical record saved.</span><Link to="/doctor" className="font-semibold">Return to dashboard</Link></motion.div>}
    <section className="mt-6 rounded-[2rem] border border-[#e1e7e2] bg-white p-6 md:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4c806c]">Patient visit</p><h1 className="mt-2 text-3xl font-semibold">{pet.name}</h1><p className="mt-1 text-sm text-[#718079]">{[pet.breed, pet.species].filter(Boolean).join(" · ")} · Owner: {appointment.owner.name}</p></div><div className="rounded-2xl bg-[#f3f7f4] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-[#87928c]">Service</p><p className="mt-1 text-sm font-semibold">{appointment.service}</p><p className="mt-1 text-xs text-[#718079]">{dateText(appointment.date)} · {appointment.status}</p></div></div></section>
    {isOnline && <section className="mt-6 rounded-[2rem] border border-[#bcd5c4] bg-[#edf5ef] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-[#285b4c]"><Video className="mr-2 inline" size={16} />Online consultation</p><p className="mt-1 text-xs text-[#52615a]">Patient is scheduled for a Google Meet call.</p></div>{appointment.googleMeetLink ? <a href={appointment.googleMeetLink} target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#173b31] px-5 py-3 text-xs font-semibold text-white"><Video size={14} />Join Google Meet</a> : <p className="text-xs text-[#718079]">Meeting link will be available before the appointment.</p>}</div></section>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[340px_1fr]"><aside className="space-y-6"><Card title="Patient information" icon={Heart}><Info label="Age" value={ageText(pet.dateOfBirth)} /><Info label="Gender" value={pet.gender || "Not recorded"} /><Info label="Weight" value={pet.weight ? `${pet.weight} kg` : "Not recorded"} /></Card><Card title="Previous medical records" icon={History}>{medicalRecords.length ? <div className="mt-5 space-y-3">{medicalRecords.map((record) => <button key={record._id} onClick={() => setSelectedRecord(record)} className="w-full rounded-2xl bg-[#f6f8f6] p-4 text-left transition hover:bg-[#edf3ee]"><p className="text-[10px] text-[#87928c]">{dateText(record.createdAt)}</p><p className="mt-1 text-xs font-semibold">{record.diagnosis || "Consultation record"}</p><p className="mt-1 text-[10px] text-[#87928c]">{record.doctor?.name || "Doctor"} · View</p></button>)}</div> : <p className="mt-5 text-xs leading-5 text-[#87928c]">No previous medical records have been recorded.</p>}</Card></aside>
      <div className="space-y-6"><Card title="Vitals" icon={Heart}><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><NumberInput label="Weight (kg)" value={form.vitals.weight} onChange={(value) => updateVital("weight", value)} /><NumberInput label="Temperature (°C)" value={form.vitals.temperature} onChange={(value) => updateVital("temperature", value)} /><NumberInput label="Heart rate (bpm)" value={form.vitals.heartRate} onChange={(value) => updateVital("heartRate", value)} /><NumberInput label="Respiratory rate (/min)" value={form.vitals.respiratoryRate} onChange={(value) => updateVital("respiratoryRate", value)} /></div></Card><TextCard title="Symptoms" value={form.symptoms} onChange={(value) => update("symptoms", value)} placeholder="Describe the patient’s symptoms..." /><TextCard title="Clinical notes" value={form.notes} onChange={(value) => update("notes", value)} placeholder="Observations and clinical notes..." /><TextCard title="Diagnosis" value={form.diagnosis} onChange={(value) => update("diagnosis", value)} placeholder="Enter diagnosis..." /><TextCard title="Treatment" value={form.treatment} onChange={(value) => update("treatment", value)} placeholder="Treatment plan and care instructions..." />
      <Card title="Prescription" icon={Pill}><div className="mt-5 space-y-3">{form.prescriptionItems.map((item, index) => <div key={index} className="grid gap-3 rounded-2xl bg-[#f6f8f6] p-4 sm:grid-cols-2"><TextInput label="Medication" value={item.medication} onChange={(value) => updatePrescription(index, "medication", value)} /><TextInput label="Dosage" value={item.dosage} onChange={(value) => updatePrescription(index, "dosage", value)} /><TextInput label="Frequency" value={item.frequency} onChange={(value) => updatePrescription(index, "frequency", value)} /><TextInput label="Duration" value={item.duration} onChange={(value) => updatePrescription(index, "duration", value)} /></div>)}</div><button onClick={() => setForm((current) => ({ ...current, prescriptionItems: [...current.prescriptionItems, { medication: "", dosage: "", frequency: "", duration: "" }] }))} className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-[#285b4c]"><Plus size={14} />Add medication</button></Card>
      <section className="flex flex-col gap-3 rounded-[2rem] bg-[#173b31] p-6 sm:flex-row"><button disabled={saving || completed} onClick={save} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-xs font-semibold text-[#173b31] disabled:opacity-60">{saved ? <><Check size={14} />Medical record saved</> : <><Save size={14} />{saving ? "Saving…" : "Save Medical Record"}</>}</button><button disabled={completed} onClick={() => setCompleteOpen(true)} className="flex flex-1 items-center justify-center gap-2 rounded-full border border-white/30 px-5 py-3 text-xs font-semibold text-white disabled:opacity-60"><Check size={14} />Complete Appointment</button></section></div></div>
  </main><AnimatePresence>{completeOpen && <Confirm onClose={() => setCompleteOpen(false)} onConfirm={complete} />}{selectedRecord && <RecordModal record={selectedRecord} onClose={() => setSelectedRecord(null)} />}</AnimatePresence></div>
}

function Card({ title, icon: Icon, children }) { return <section className="rounded-[2rem] border border-[#e1e7e2] bg-white p-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e6f0e9] text-[#285b4c]"><Icon size={17} /></div><h2 className="font-semibold">{title}</h2></div>{children}</section> }
function TextCard({ title, value, onChange, placeholder }) { return <Card title={title} icon={FileText}><textarea value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-5 min-h-28 w-full resize-y rounded-2xl border border-[#dfe6e1] bg-[#fafbfa] p-4 text-sm outline-none focus:border-[#4c806c]" /></Card> }
function Info({ label, value }) { return <div className="mt-4 flex justify-between border-b border-[#edf0ed] pb-3 text-xs last:border-0"><span className="text-[#87928c]">{label}</span><span className="font-semibold">{value}</span></div> }
function NumberInput({ label, value, onChange }) { return <label className="block text-[10px] font-semibold text-[#52615a]">{label}<input type="number" min="0" step="any" value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe6e1] bg-[#fafbfa] px-3 py-2.5 text-sm outline-none focus:border-[#4c806c]" /></label> }
function TextInput({ label, value, onChange }) { return <label className="block text-[10px] font-semibold text-[#52615a]">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe6e1] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#4c806c]" /></label> }
function Confirm({ onClose, onConfirm }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-[#17221e]/40 p-5"><motion.div initial={{ y: 12 }} animate={{ y: 0 }} exit={{ y: 12 }} className="w-full max-w-md rounded-[2rem] bg-white p-7"><h2 className="text-xl font-semibold">Complete appointment?</h2><p className="mt-3 text-sm leading-6 text-[#718079]">Once completed, this appointment will move to your completed visits.</p><div className="mt-7 flex gap-3"><button onClick={onClose} className="flex-1 rounded-full border border-[#dfe6e1] py-3 text-xs font-semibold">Keep Appointment</button><button onClick={onConfirm} className="flex-1 rounded-full bg-[#173b31] py-3 text-xs font-semibold text-white">Complete Visit</button></div></motion.div></motion.div> }
function RecordModal({ record, onClose }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-[#17221e]/40 p-5"><div className="w-full max-w-lg rounded-[2rem] bg-white p-7"><button onClick={onClose} className="float-right"><X size={17} /></button><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#4c806c]">{dateText(record.createdAt)}</p><h2 className="mt-2 text-xl font-semibold">{record.diagnosis || "Consultation record"}</h2><div className="mt-5 space-y-4 text-sm"><Detail label="Symptoms" value={record.symptoms} /><Detail label="Clinical notes" value={record.notes} /><Detail label="Treatment" value={record.treatment} /><Detail label="Prescription" value={record.prescription} /></div></div></motion.div> }
function Detail({ label, value }) { return <div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#87928c]">{label}</p><p className="mt-1 whitespace-pre-wrap text-[#52615a]">{value || "Not recorded"}</p></div> }
function Message({ title, detail }) { return <div className="grid min-h-screen place-items-center bg-[#f7f8f5] p-5 text-center"><div className="max-w-md rounded-[2rem] border border-[#e1e7e2] bg-white p-8"><Stethoscope className="mx-auto text-[#4c806c]" /><h1 className="mt-4 text-xl font-semibold">{title}</h1><p className="mt-3 text-sm text-[#718079]">{detail}</p><Link to="/doctor" className="mt-6 inline-block rounded-full bg-[#173b31] px-5 py-3 text-xs font-semibold text-white">Back to dashboard</Link></div></div> }
function LoadingWorkspace() { return <div className="min-h-screen bg-[#f7f8f5] p-6 md:p-10"><div className="mx-auto max-w-7xl space-y-6 animate-pulse"><div className="h-8 w-40 rounded bg-[#e6ece7]" /><div className="h-44 rounded-[2rem] bg-white" /><div className="grid gap-6 xl:grid-cols-[340px_1fr]"><div className="h-80 rounded-[2rem] bg-white" /><div className="h-96 rounded-[2rem] bg-white" /></div></div></div> }
